services:
  tic-tac-toe-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    image: shovon668/tic-tac-toe:dev
    container_name: tic-tac-toe-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tic-tac-toe-dev-network
    restart: unless-stopped
    command: npm run dev

networks:
  tic-tac-toe-dev-network:
    driver: bridge