name: List Changed Files
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List changed files since last commit
        run: |
          git diff --name-only HEAD^ HEAD || echo 'No previous commit.'
